name: CI
on:
  pull_request:
    branches:
      - master

jobs:
  flutter_test:
    runs-on: windows-latest
    name: Run Flutter Tests and analyze
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test

  build_appbundle:
    name: Build Android App Bundle
    needs: [flutter_test]
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter clean
      - run: flutter pub get
      - run: flutter build appbundle

