name: CI
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  flutter_test:
    runs-on: ubuntu-latest
    name: Run Flutter Tests and analyze
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test

